construction/project-master/posts/urls.py
from django.urls import path
from posts import views

app_name = "posts"

urlpatterns = [
	path('list', views.PostListView.as_view(), name="list"),
 	path('create/', views.PostCreateUpdateView.as_view(), name='create'),
 	path('<str:slug>/', views.PostDetailView.as_view(), name='detail'),
 	path('<str:slug>/edit/', views.PostCreateUpdateView.as_view(), name='update'),
 	# path('<slug>/delete/', views.post_delete),
]

construction/project-master/project/urls.py
from django.urls import include, path
from django.contrib import admin
from mains.views import HomeView, about_view, privacy_policy_view, ContactView, PurchaseHistoryView

from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "FOUR SQUARE RENTAL"
admin.site.site_title = "FOUR SQUARE RENTAL Admin Portal"
admin.site.index_title = "Welcome to FOUR SQUARE RENTAL Portal"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("contact/", ContactView.as_view(), name="contact"),
    path("agents/", include("agents.urls", namespace="agents")),
    path("", HomeView.as_view(), name="home"),
    path("property/",include('properties.urls',namespace='properties')),
    path("purchase-history/", PurchaseHistoryView.as_view(), name="purchase_history"),
    path("accounts/", include('allauth.urls')),
    path("about/", about_view,name="about"),
    path("privacy_policy/", privacy_policy_view,name="privacy_policy"),
    path("blog/", include('posts.urls', namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

construction/project-master/properties/urls.py
from django.urls import path
from properties.views import RemoveFromPurchaseList, CheckoutPurchaseView, RentPropertyView, BuyPropertyListView, RentPropertyListView, PostInspectionView, PropertyView, BuyPropertyView


app_name = "properties"


urlpatterns=[
  path("remove/<int:pk>/<str:type>/", RemoveFromPurchaseList.as_view(), name='remove_property'),
  path("detail/<str:slug>/", PropertyView.as_view(), name='individual_property'),
  path("buy-list/", BuyPropertyListView.as_view(), name='buy_property_list'),
  path("rent-list/", RentPropertyListView.as_view(), name='rent_property_list'),
  path("inspection/<int:pk>/", PostInspectionView.as_view(), name='property_inspection'),
  path("buy/<int:pk>/", BuyPropertyView.as_view(), name='property_buy'),
  path("rent/<int:pk>/", RentPropertyView.as_view(), name='property_rent'),
  path("checkout/", CheckoutPurchaseView.as_view(), name='checkout_purchase'),
]

construction/project-master/properties/models.py
from django.db import models
from django.urls import reverse
import re

# Create your models here.
from django.conf import settings
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.core.exceptions import ValidationError
from agents.models import Agent


def upload_location(instance,filename):
	  return "%s/%s" %(instance, filename)


def phone_validator(value):
    reg = re.compile(r'^\d\d\d\d\d\d\d\d\d\d$')
    number = reg.match(value)
    if number is None:
      raise ValidationError("The number is not valid")
    return value

choices = (('sell', 'sell'), ('rent', 'rent'))

class Property(models.Model):
    name = models.CharField(max_length=30)
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True,null=True)
    type = models.CharField(max_length=20, choices=choices, default='sell')
    description = models.TextField(max_length=400,null=True)
    price = models.IntegerField()
    timestamp = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to=upload_location)
    view_count = models.IntegerField(default=0)
    sold = models.BooleanField(default=False)

    class Meta:
        ordering = ['-timestamp']
        verbose_name_plural = "Properties"

    def raise_view_count(self):
        self.view_count = self.view_count +1
        return True

    def get_absolute_url(self):
        return reverse("properties:individual_property", kwargs={"slug": self.slug})

    def __str__(self):
        return "%s" % self.name


class OrderProperty(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='orderuser', on_delete=models.CASCADE)
    property = models.ForeignKey(Property, related_name='property', on_delete=models.CASCADE)
    message = models.TextField(max_length=200)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-timestamp']
        verbose_name_plural = "Ordered Properties"

    def total_price(self):
      marked_price = float(self.property.price)
      return marked_price

    def __str__(self):
        return self.property.name


class RentProperty(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='rent_user', on_delete=models.CASCADE)
    property = models.ForeignKey(Property, related_name='rent_property', on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    message = models.TextField(max_length=200, null=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-timestamp']
        verbose_name_plural = "Rented Properties"

    def __str__(self):
        return self.property.name


class InspectProperty(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='inspect_user', on_delete=models.CASCADE)
    property = models.ForeignKey(Property, related_name='inspect_property', on_delete=models.CASCADE)
    inspect_datetime = models.DateTimeField()
    message = models.TextField(max_length=200, null=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)

    class Meta:
        ordering = ['-timestamp']
        verbose_name_plural = "Inspected Properties"

    def __str__(self):
        return self.property.name


def create_slug(instance, new_slug=None):
    slug = slugify(instance.name)
    if new_slug is not None:
      slug = new_slug
    qs = Property.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
      new_slug = "%s-%s" %(slug, qs.first().id)
      return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
      instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Property)

construction/project-master/properties/forms.py
from django import forms
from .models import OrderProperty, InspectProperty


class PropertyRentForm(forms.ModelForm):
    start_date = forms.DateTimeField(label='Datetime', widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}), required=False)
    
    class Meta:
        model = OrderProperty
        fields = [
          'start_date',
          'message',
        ]


class PropertyInspectForm(forms.ModelForm):
    inspect_datetime = forms.DateTimeField(label='Datetime', widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}), required=False)
    
    class Meta:
        model = InspectProperty
        fields = [
          'inspect_datetime',
          'message',
        ]

construction/project-master/properties/views.py
from django.shortcuts import render, redirect, reverse
from .models import Property, OrderProperty, InspectProperty, RentProperty
from .forms import PropertyInspectForm, PropertyRentForm
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings 
from django.views.generic import ListView, View, DetailView

# Create your views here.

class PropertyView(DetailView):
    model = Property
    template_name = 'individual.html'
    context_object_name = 'property'

    def get_context_data(self, **kwargs):
        ctx = super(PropertyView, self).get_context_data(**kwargs)
        ctx['rent_form'] = PropertyRentForm(self.request.GET or None)
        ctx['inspect_form'] = PropertyInspectForm(self.request.GET or None)
        obj = self.get_object()
        if self.request.user.is_authenticated:
            ctx['is_under_inspect'] = True if InspectProperty.objects.filter(user=self.request.user, property=obj).count() > 0 else False
        return ctx


class BuyPropertyListView(ListView):
    model = Property
    template_name = 'buy-property.html'
    paginate_by = 10

    def get_queryset(self):
        qs = Property.objects.filter(type='sell', sold=False)
        return qs


class RentPropertyListView(ListView):
    model = Property
    template_name = 'rent-property.html'
    paginate_by = 10

    def get_queryset(self):
        qs = Property.objects.filter(type='rent', sold=False)
        return qs


class PostInspectionView(View):

    def post(self, request, *args, **kwargs):
        data = request.POST
        obj = InspectProperty(
          user=request.user,
          property_id=self.kwargs.get('pk'),
          inspect_datetime=data.get('inspect_datetime'),
          message=data.get('message'),
        )
        obj.save()
        messages.success(request, "You have successfully ordered an inspection. We will get back to you soon.")
        return redirect(reverse('home'))


class BuyPropertyView(View):
    def get(self, request, *args, **kwargs):
        property = Property.objects.get(id=self.kwargs.get('pk'))
        if OrderProperty.objects.filter(user=request.user, property=property, paid=False):
            messages.warning(request, "You have already placed an order for this property. Consider checkout.")
            return redirect(reverse('home'))
        obj = OrderProperty(
          user=request.user,
          property=property,
          message='Property Bought',
        )
        obj.save()
        messages.success(request, "You have successfully ordered a product. Please proceed to checkout")
        return redirect(reverse('home'))


class RentPropertyView(View):
    def post(self, request, *args, **kwargs):
        property = Property.objects.get(id=self.kwargs.get('pk'))
        data = request.POST
        if RentProperty.objects.filter(user=request.user, property=property, paid=False):
            messages.warning(request, "You have already placed an order for this property. Consider checkout.")
            return redirect(reverse('home'))
        obj = RentProperty(
          user=request.user,
          property=property,
          start_date=data.get('start_date'),
          message=data.get('message')
        )
        obj.save()
        messages.success(request, "You have successfully rented a product. Please proceed to checkout")
        return redirect(reverse('home'))


class CheckoutPurchaseView(View):
    def get(self, request, *args, **kwargs):
        rent_objs = RentProperty.objects.filter(user=request.user)
        buy_objs = OrderProperty.objects.filter(user=request.user)
        for rent in rent_objs:
            rent.paid = True
            property = rent.property
            property.sold = True
            property.save()
            rent.save()
        for buy in buy_objs:
            buy.paid = True
            property = buy.property
            property.sold = True
            property.save()
            buy.save()
        messages.success(request, "You have successfully purchased a product.")
        return redirect(reverse('home'))


class RemoveFromPurchaseList(View):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        type = self.kwargs.get('type')
        if type == 'rent':
            RentProperty.objects.filter(pk=pk).delete()
        else:
            OrderProperty.objects.filter(pk=pk).delete()
        messages.success(request, "You removed a product from your booking list. Please continue shopping.")
        return redirect(reverse('home'))

construction/project-master/properties/templates/buy-property.html
{% extends "base.html" %}
{% block title %}Four Square Rentals | Buy Properties{% endblock title %}

{% block page_title %}Buy Properties{% endblock page_title %}
{% block buy_property %}w3-dark-grey{% endblock %}

{% block content %}
<div class="w3-row">
  {% for each in object_list %}
  <div class="w3-col l3 m6 w3-mobile w3-margin-bottom">
    <div class="w3-container">
      <div class="w3-display-container">
        <img alt="{{ each.name }}" src="{{ each.image.url }}" style="height: 260px;width:100%;object-fit:cover;">
        <!-- <span class="w3-tag w3-display-topleft">New</span> -->
        <div class="w3-display-middle w3-display-hover">
          <a href="{{ each.get_absolute_url }}">
          <button class="w3-button w3-red">View&nbsp;<i class="fa fa-arrows"></i></button>
          </a>
        </div>
      </div>
      <div style="padding-top: 10px;">
        <h3><small>{{ each.name|truncatechars_html:15 }}</small></h3> <p><small>Rs: {{ each.price }}/-</small></p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<div class="pagination">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>

{% endblock content %}

construction/project-master/properties/templates/individual.html
{% extends "base.html" %}
{% block title %} Four Square Rental | {{ property.name }} {% endblock title %}
{% block page_title %} Property {% endblock page_title %}
{% load crispy_forms_tags %}

<!-- for the meta data to base file  -->
{% block meta_head %}
  {{ property.name }}. {{ property.description }}
{% endblock meta_head %}

{% block content %}
<div class="w3-row">
  <div class="w3-half w3-grey w3-container" style="padding-top: 16px;">
    <div class="w3-left">
        <img alt="{{ property.name }}" src="{{ property.image.url }}" class="w3-left" alt="{{ property.name }}" style="width:100%">
      </div>
  </div>
  <div class="w3-half">
    <div class="w3-left-align w3-padding-large">
        <div style="display: flex; justify-content: space-between;">
          <h2 class="w3-text-black">{{ property.name }}</h2>
          {% if is_under_inspect %}
          <div style="display: flex; align-items: center;">
            <small style="padding: 0 3px;" class="w3-yellow">your inspection</small>
          </div>
          {% endif %}
        </div>
        <p style="padding:0;margin:3px 0; display: flex; justify-content: space-between;"><strong>Property Id :</strong><span>{{ property.pk }}-{{ property.slug }}</span></p>
        <p style="padding:0;margin:3px 0; display: flex; justify-content: space-between;"><strong>Price :</strong><span>$ <span class="w3-text-red">{{ property.price }}</span> /-</span></p>
        {% if property.description %}
          <p class="w3-margin-top"><strong>Property Details </strong>:<br><span class="w3-text-grey">{{ property.description }}</span></p>
        {% endif %}
        
        <h3 class="w3-text-black w3-margin-top">Agent Information</h3>
        <p style="padding:0;margin:3px 0; display: flex; justify-content: space-between;"><strong>Name :</strong><span>{{ property.agent.name }}</span></p>
        <p style="padding:0;margin:3px 0; display: flex; justify-content: space-between;"><strong>Phone :</strong><span>{{ property.agent.phone_number }}</span></p>
        <p style="padding:0;margin:3px 0; display: flex; justify-content: space-between;"><strong>Email :</strong><span>{{ property.agent.email }}</span></p>
        <p style="padding:0;margin:3px 0; display: flex; justify-content: space-between;"><strong>Address :</strong><span>{{ property.agent.total_address }}</span></p>
        <div style="width: 100%; display: flex; justify-content: flex-end;">          
          {% if not property.sold %}
            {% if request.user.is_authenticated %}
              {% if not is_under_inspect %}
              <button style="margin-right: 10px;" onclick="document.getElementById('id01').style.display='block'" class="w3-btn w3-margin-top w3-green">Book a Inspectation</button>
              {% endif %}
              {% if property.type == 'rent' %}
              <button onclick="document.getElementById('id02').style.display='block'" class="w3-btn w3-margin-top w3-black">Rent Now</button>
              {% else %}
              <a href="{% url 'properties:property_buy' property.pk %}" class="w3-btn w3-margin-top w3-black">Buy Now</a>
              {% endif %}
            {% else %}
              <a href="{% url 'account_login' %}"><button class="w3-margin-top w3-btn w3-red">Book Now</button></a>
            {% endif %}
          {% endif %}
        </div>
      </div>
  </div>
</div>
<br>
{% endblock content %}

{% block modal %}
<div id="id01" class="w3-modal" style="z-index:5;">
  <div class="w3-modal-content">
    <div class="w3-container w3-padding w3-red">
       <span onclick="document.getElementById('id01').style.display='none'"
       class="w3-button w3-red w3-right w3-xxlarge"><i class="fa fa-remove"></i></span>
      <h1>Inspection Form</h1>
    </div>
    <div class="w3-panel">
      <div style="width: 100%; display: flex; justify-content: flex-end;">
        <div><b>Price</b> : $ <span class="w3-text-red">{{ property.price }}</span> /-<br></p></div>
      </div>      
      <form action="{% url 'properties:property_inspection' property.pk %}" method="POST">{% csrf_token %}
      {{ inspect_form|crispy }}
      <div class="w3-section">
        <button class="w3-button w3-red w3-right w3-margin-bottom" type="submit">Submit<i class="fa fa-paper-plane"></i></button> 
      </div> 
      </form>
    </div>
  </div>
</div>

<div id="id02" class="w3-modal" style="z-index:5">
  <div class="w3-modal-content">
    <div class="w3-container w3-padding w3-red">
       <span onclick="document.getElementById('id02').style.display='none'"
       class="w3-button w3-red w3-right w3-xxlarge"><i class="fa fa-remove"></i></span>
      <h1>Rent Form</h1>
    </div>
    <div class="w3-panel">
      <div style="width: 100%; display: flex; justify-content: flex-end;">
        <div><b>Price</b> : $ <span class="w3-text-red">{{ property.price }}</span> /-<br></p></div>
      </div>      
      <form action='{% url 'properties:property_rent' property.pk %}' method="POST">{% csrf_token %}
      {{ rent_form|crispy }}
      <div class="w3-section">
        <button class="w3-button w3-red w3-right w3-margin-bottom" type="submit">Submit<i class="fa fa-paper-plane"></i></button> 
      </div> 
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block javascript %}
  {{ block.super }}
  <script>
    $(document).ready(function(){
      // popover for error
      if ($(".form-group").hasClass("has-error")){
        $("#id01").show();
      }
    });
  </script>
{% endblock %}

construction/project-master/properties/templates/rent-property.html
{% extends "base.html" %}
{% block title %}Four Square Rentals | Rent Properties{% endblock title %}

{% block page_title %}Rent Properties{% endblock page_title %}
{% block rent_property %}w3-dark-grey{% endblock %}

{% block content %}
<div class="w3-row">
  {% for each in object_list %}
  <div class="w3-col l3 m6 w3-mobile w3-margin-bottom">
    <div class="w3-container">
      <div class="w3-display-container">
        <img alt="{{ each.name }}" src="{{ each.image.url }}" style="height: 260px;width:100%;object-fit:cover;">
        <!-- <span class="w3-tag w3-display-topleft">New</span> -->
        <div class="w3-display-middle w3-display-hover">
          <a href="{{ each.get_absolute_url }}">
          <button class="w3-button w3-red">View&nbsp;<i class="fa fa-arrows"></i></button>
          </a>
        </div>
      </div>
      <div style="padding-top: 10px;">
        <h3><small>{{ each.name|truncatechars_html:15 }}</small></h3> <p><small>Rs: {{ each.price }}/-</small></p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<div class="pagination">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>

{% endblock content %}