construction/project-master/posts/urls.py
from django.urls import path
from posts import views

app_name = "posts"

urlpatterns = [
	path('list', views.PostListView.as_view(), name="list"),
 	path('create/', views.PostCreateUpdateView.as_view(), name='create'),
 	path('<str:slug>/', views.PostDetailView.as_view(), name='detail'),
 	path('<str:slug>/edit/', views.PostCreateUpdateView.as_view(), name='update'),
 	# path('<slug>/delete/', views.post_delete),
]

construction/project-master/project/urls.py
from django.urls import include, path
from django.contrib import admin
from mains.views import HomeView, about_view, privacy_policy_view, ContactView, PurchaseHistoryView

from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "FOUR SQUARE RENTAL"
admin.site.site_title = "FOUR SQUARE RENTAL Admin Portal"
admin.site.index_title = "Welcome to FOUR SQUARE RENTAL Portal"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("contact/", ContactView.as_view(), name="contact"),
    path("agents/", include("agents.urls", namespace="agents")),
    path("", HomeView.as_view(), name="home"),
    path("property/",include('properties.urls',namespace='properties')),
    path("purchase-history/", PurchaseHistoryView.as_view(), name="purchase_history"),
    path("accounts/", include('allauth.urls')),
    path("about/", about_view,name="about"),
    path("privacy_policy/", privacy_policy_view,name="privacy_policy"),
    path("blog/", include('posts.urls', namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

construction/project-master/posts/models.py
from __future__ import unicode_literals
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.contrib.contenttypes.models import ContentType
from .utils import get_read_time


def upload_location(instance, filename):
	  return "%s/%s" %(instance.title, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    title = models.CharField(max_length=130)
    slug = models.SlugField(blank=True,unique=True)
    image = models.ImageField(
      upload_to=upload_location , 
      null=True,
      blank=True,
      )
    content = models.TextField()
    draft = models.BooleanField(default=False)
    read_time = models.IntegerField(default=0,blank=True,null=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    view_count = models.IntegerField(default=0,null=True)
    approval = models.BooleanField(default=False)

    def __str__(self):
      return self.title

    @property
    def raise_view_count(self):
        self.view_count = self.view_count +1
        return True

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'slug':self.slug})

    class Meta:
        ordering = ['-timestamp', '-updated']
      

def create_slug(instance,new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
      slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists() 
    if exists:
      new_slug = "%s-%s" %(slug,qs.first().id)
      return create_slug(instance,new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender,instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.content
        read_time = get_read_time(html_string)
        instance.read_time = read_time 


pre_save.connect(pre_save_post_receiver, sender=Post)

construction/project-master/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    content = forms.Textarea()
    
    class Meta:
        model = Post
        fields = [
          'title',
          'content',
          'image',
          'draft',
        ]
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "w3-input w3-border"}
            )
        }

construction/project-master/posts/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect 
from django.contrib import messages

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.utils import timezone 
from django.views.generic import View, ListView, DetailView, UpdateView

from .models import Post
from .forms import PostForm

from django.db.models import Q
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse_lazy


class PostCreateUpdateView(UpdateView):
    model = Post
    template_name = "post_form.html"
    form_class = PostForm
    success_url = reverse_lazy("posts:list")

    def form_valid(self, form):
        if form.instance.slug:
            form.instance.updated_by = self.request.user
        else:
            form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_initial(self):
        initial = super(PostCreateUpdateView, self).get_initial()
        return initial

    def get_object(self, queryset=None):
        if self.kwargs.get("slug"):
            return super(PostCreateUpdateView, self).get_object()
        return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'

    def get_context_data(self, **kwargs):
        ctx = super(PostDetailView, self).get_context_data(**kwargs)
        ctx['popular_posts'] = Post.objects.filter(view_count__gte=20)
        # import ipdb; ipdb.set_trace()
        return ctx


class PostListView(ListView):
    model = Post
    template_name = 'homepage.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        qs = self.get_queryset()
        query=request.GET.get("q")
        if query:
            qs = qs.filter(
              Q(title__icontains=query) |
              Q(content__icontains=query) |
              Q(user__first_name__icontains=query)|
              Q(user__last_name__icontains=query)
            ).distinct()
        self.object_list = qs
        context = self.get_context_data(object_list=self.object_list)
        return render(request, self.template_name, context=context)
    
    def get_queryset(self):
        qs = Post.objects.filter(draft=False)
        return qs

    def get_context_data(self, **kwargs):
        ctx = super(PostListView, self).get_context_data(**kwargs)
        ctx['popular_posts'] = self.get_queryset().filter(view_count__gte=20)
        return ctx

construction/project-master/posts/templates/blog.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <title>{% block head_title %}{% endblock head_title %}</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="{% static 'css/blog.css' %}"/>
  <link rel="shortcut icon" href="{% static 'logo.png' %}" type="image/png">
  {% block head_extra %}{% endblock head_extra %}
  <style>
  h1,h2,h3,h4,h5,h6 {font-family: "Oswald"}
  body {font-family: "Open Sans"}

  {% block styling %}

  {% endblock styling %}

  </style>
</head>

<body class="w3-light-grey">
{% include 'messages_display.html' %}
  <div class="w3-bar w3-black">
    <a href="#" class="w3-bar-item w3-button"><i class="fa fa-facebook-official"></i></a>
    <a href="#" class="w3-bar-item w3-button"><i class="fa fa-instagram"></i></a>
    <a href="#" class="w3-bar-item w3-button"><i class="fa fa-pinterest"></i></a>
    {% if not request.user.is_authenticated %}
          <a href="{% url 'account_signup' %}" class="w3-bar-item w3-button w3-right">Sign Up</a>
          <a href="{% url 'account_login' %}" class="w3-bar-item w3-button w3-right">Login</a>
          {% else %}
          <a href="{% url 'account_logout' %}" class="w3-bar-item w3-button w3-right">Logout</a>
    {% endif %}
  </div>
<div class="w3-content" style="max-width:1600px">
  {% block page_header %}{% endblock %}
  {% block content %}{% endblock content %}
<footer class="w3-container w3-dark-grey" style="padding:32px">
  <a href="#" class="w3-button w3-black w3-padding-large w3-margin-bottom"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
  <p>copyright ©2020</p>
</footer>
{% block javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
</body>
</html>

construction/project-master/posts/templates/comment_thread.html
{% extends "blog.html" %}
{% load crispy_forms_tags %}

{% block head_title %}

{{ instance.title }}

{% endblock head_title %}

{% block content %}
	<div class="w3-row w3-padding w3-border">
	
				<a href="#" style="text-decoration: none; color: #365899;">{{ comment.user }}</a>
					<p>{{ comment.content }}</p>
				<small id="inline">{{ comment.timestamp|timesince }} ago</small> | 

				 {% if comment.children.count > 0 %} 
				 {{ comment.children.count }} comment{% if comment.children.count > 1 %}s{% endif %} |
				 {% endif %}

				 {% if request.user == comment.user %}
				 <small id="inline"><a href="{{ comment.get_delete_url }}">Delete</a></small>
				 {% endif %}
				 <hr/> 

				<div>
					{% for child_comment in comment.children %}
					<blockquote>
						<a href="#" style="text-decoration: none; color: #365899;">{{ child_comment.user }}</a>
							<p>{{ child_comment.content }}</p>	
						<small id="inline"> {{ child_comment.timestamp|timesince }} ago |</small>{% if request.user == child_comment.user %}<small id="inline"><a href="{{ child_comment.get_delete_url }}"> Delete</a></small>{% endif %}
					</blockquote>
					{% endfor %}

					{% if request.user.is_authenticated %}
					<form method="POST" class="w3-container" action=".">{% csrf_token %}

						{{ form|crispy }}

						<input type="hidden" name="parent_id" value="{{ comment.id }}">

						<button class="w3-button w3-blue" type="submit">Reply</button>
					</form>
					{% else %}
					<p> you must login to comment </p>
					{% endif %}
				</div>

			<hr/>

	</div>
{% endblock content %}

construction/project-master/posts/templates/confirm_delete.html
{% extends "blog.html" %}
{% load crispy_forms_tags %}

{% block head_title %}

{{ instance.title }}  
{% endblock head_title %}

{% block content %}
	<div class="w3-row w3-padding w3-border">
		<div class="w3-center">
			<h1>Confirm your Delete.</h1>
			<p>Are you sure you want to delete "{{ object.content }}"?</p>
			<form method="POST" action=''>{% csrf_token %}
			<button class="w3-button w3-red w3-border" type="submit">Delete</button>
			</form>
			<a href="{{ object.get_absolute_url }}"><button class="w3-button w3-border">Cancle</button></a>
		</div>
	</div>

			<hr/>
{% endblock content %}

construction/project-master/posts/templates/form.html
{% extends "blog.html" %}


{% block head_title %}Login {% endblock head_title %}


{% load crispy_forms_tags %}


{% block content %}

 <div class="w3-row w3-padding w3-border">

	<h1>{{ title }}</h1>
	{% if not request.user.is_authenticated %}
	<form method="POST" class="w3-container" action="" enctype="multipart/form-data">{% csrf_token %}
	{{ form | crispy }}
	<button type="submit" class='w3-button w3-btn'>Submit</button>
	</form>
	{% else %}
	<h5> you are already logged in. </h5>
	{% endif %}
</div>

{% endblock content %}

construction/project-master/posts/templates/homepage.html
{% extends 'blog.html' %}
{% load static %}

{% block head_title %}Four Square Rentals | Blog{% endblock head_title %}
{% block page_header %}
<header class="w3-container w3-center w3-padding-16 w3-white">
  <div class="w3-row">
      <div class="w3-col l8 m6">
        <a href="{% url 'posts:list' %}" style=" text-decoration: none;">
          <h1><b>Blog</b></h1>
          <h6>Blogs of <span class="w3-tag w3-red">FSR</span></h6>
        </a>
        {% if request.user.is_authenticated %}
          <div style="padding-bottom: 8px;">
              <a href="{% url 'posts:create' %}"><button class="w3-btn w3-blue"><i class="fa fa-edit"></i>Create Post</button></a>
          </div>
          {% else %}
          <div style="padding-bottom: 8px;">
              <a href="{% url 'account_login' %}"><button class="w3-btn w3-blue"><i class="fa fa-edit"></i>Login</button></a><h5>to create your own blog.</h5>
          </div>

        {% endif %}
      </div>
      <div class="w3-col l4 m6">
          <form method="GET" action=''>{% csrf_token %}
            <div class="w3-container" style="display: flex;">
              <input class="w3-input w3-border" type="text" placeholder="Keyword..." name="q" value={{ request.GET.q }}>
              <button class="w3-btn w3-right w3-black w3-card" type="submit">Search</button>
            </div>
          </form>
      </div>
  </div>
</header>
{% endblock %}

{% block content %}
  <div class="w3-row w3-padding w3-border">

    <!-- Blog entries -->
    <div class="w3-col l8 s12">
    
      <!-- Blog entry -->
      {% for object in object_list %}

      <div class="w3-container w3-white w3-margin w3-padding-large">
        <div class="w3-center">
          <h3><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h3>
          <h5><span class="w3-opacity">- {{ object.timestamp|timesince }} ago </span></h5>
        </div>

        <div class="w3-justify">
          {% if object.image %}
            <img style="width: 100%;" src="{{ object.image.url }}" alt="Girl Hat" class="w3-padding-16 blogs">
          {% endif %}
          <p><strong></strong>{{ object.content|safe|truncatechars_html:200 }} <a style="color: #365899;" href="{{ object.get_absolute_url }}">Read more..</a></p>
          <p class="w3-clear"></p>
        </div>
      </div>
      <hr>

      {% endfor %}

      <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
      
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
      
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
      </div>

    </div>

    <!-- About/Information menu -->
    <div class="w3-col l4">
      <!-- About Card -->
      <div class="w3-white w3-margin">
        
        <div class="w3-center">
          <a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="mellif cake logo" style="width: 100%;" class="w3-border"></a>
        </div>

        <div class="w3-container w3-black">
          <h4>Four Square Rentals</h4>
          <p>Team Four Square Rentals has been working on improving the quality of food in kathmandu for the price people pay for it. We are working on making people's everyday lifestyle easier by providing them easy access to recipes and to our products in reasonable price.</p>
        </div>
      </div>
      <hr>

      <!-- Posts -->
      <div class="w3-white w3-margin">
        <div class="w3-container w3-padding w3-black">
          <h4>Popular Posts</h4>
        </div>

        <ul class="w3-ul w3-hoverable w3-white w3-container w3-margin-bottom">
          {% for item in popular_posts %}

          <li class="w3-padding w3-margin-bottom">
            <img src="{{ item.image.url }}" alt="{{ item.title }}" class="w3-left w3-margin-right" style="width:50px">
            <a href="{{ item.get_absolute_url }}" style="text-decoration: none;"><span class="w3-large" style="color: #365899;">{{ item.title }}</span></a>
            <br>
          </li>

          {% endfor %}
        </ul>
      </div>

      <!-- follow links -->
      <div class="w3-white w3-margin">
        <div class="w3-container w3-padding w3-black">
          <h4>Follow Us</h4>
        </div>
        <div class="w3-container w3-xlarge w3-padding">
          <a href="https://www.facebook.com/mellif.cake/"><i class="fa fa-facebook-official w3-hover-opacity"></i></a>
          <a href="https://www.instagram.com/mellif.cake/"><i class="fa fa-instagram w3-hover-opacity"></i></a>
          <a href="https://www.pinterest.com/mellifcake/"><i class="fa fa-pinterest-p w3-hover-opacity"></i></a>
        </div>
      </div>
      <hr>
      
    <!-- END About/Intro Menu -->
    </div>

  <!-- END GRID -->
  </div>

{% endblock content %}

construction/project-master/posts/templates/messages_display.html
{% if messages %}
	<div class="messages">
		<ul class="messages">
			{% for message in messages %}
			<li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{% if "html_safe" in message.tags %} {{ message|safe }} {% else %} {{ message }} {% endif %}</li>
			{% endfor %}
		</ul>
	</div>
{% endif %}

construction/project-master/posts/templates/post_detail.html
{% extends "blog.html" %}
{% load crispy_forms_tags static %}
{% block head_title %}{{ object.title }}{% endblock head_title %}

{% block page_header %}
<header class="w3-container w3-center w3-padding-16 w3-white">
  <div class="w3-row">
      <div class="w3-col l8 m6">
        <a href="{% url 'posts:list' %}" style=" text-decoration: none;">
          <h1><b>{{ object.title }}</b> <small> {% if object.draft %} <i style="color: red;">Draft</i>{% endif %}</h1>
        </a>
        <P><small>Read Time: {{ object.read_time }} minutes.</small></P>
        <p> Author: {{ object.user.get_full_name }} </p>
        {% if request.user.is_authenticated %}
          {% if request.user == object.user %}
          <div style="padding-bottom: 8px;">
            <a href="{% url 'posts:update' object.slug %}" class="w3-button w3-blue" role="button">Edit <i class="fa fa-edit"></i></a>
          </div>
          {% endif %}
        {% endif %}
      </div>
  </div>
</header>
{% endblock %}

{% block content %}
  <div class="w3-row w3-padding w3-border">
    <div class="w3-col l8 s12">
      <div class="w3-container w3-white w3-margin w3-padding-large">
        <div class="w3-justify">
          {% if object.image %}
            <img src="{{ object.image.url }}" alt="{{ object.title }}" style="width: 100%;" class="w3-padding-16 blogs">
          {% endif %}
          <div id="blogContent">
            {% autoescape off %}
              {{ object.content }}
            {% endautoescape %}
          </div>
          <p class="w3-clear"></p>
        </div>
        <hr>
      </div>
      <hr>
    </div>

    <!-- About/Information menu -->
    <div class="w3-col l4">
      <!-- About Card -->
      <div class="w3-white w3-margin">
        
        <div class="w3-center">
          <a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="mellif cake logo" style="width: 100%;" class="w3-border"></a>
        </div>

        <div class="w3-container w3-black">
          <h4>Four Square Rentals</h4>
          <p>Team Four Square Rentals has been working on improving the quality of food in kathmandu for the price people pay for it. We are working on making people's everyday lifestyle easier by providing them easy access to recipes and to our products in reasonable price.</p>
        </div>
      </div>
      <hr>

      <!-- Posts -->
      <div class="w3-white w3-margin">
        <div class="w3-container w3-padding w3-black">
          <h4>Popular Posts</h4>
        </div>

        <ul class="w3-ul w3-hoverable w3-white w3-container w3-margin-bottom">
          {% for item in popular_posts %}

          <li class="w3-padding w3-margin-bottom">
            <img src="{{ item.image.url }}" alt="{{ item.title }}" class="w3-left w3-margin-right" style="width:50px">
            <a href="{{ item.get_absolute_url }}" style="text-decoration: none;"><span class="w3-large" style="color: #365899;">{{ item.title }}</span></a>
            <br>
          </li>

          {% endfor %}
        </ul>
      </div>
      <hr>
      <!-- follow links -->
      <div class="w3-white w3-margin">
        <div class="w3-container w3-padding w3-black">
          <h4>Follow Us</h4>
        </div>
        <div class="w3-container w3-xlarge w3-padding">
          <a href="https://www.facebook.com/mellif.cake/"><i class="fa fa-facebook-official w3-hover-opacity"></i></a>
          <a href="https://www.instagram.com/mellif.cake/"><i class="fa fa-instagram w3-hover-opacity"></i></a>
          <a href="https://www.pinterest.com/mellifcake/"><i class="fa fa-pinterest-p w3-hover-opacity"></i></a>
        </div>
      </div>
      <hr>
    </div>
</div>
	
{% endblock content %}

construction/project-master/posts/templates/post_form.html
{% extends "blog.html" %}
{% block head_title %} Create Blog Post | Four Square Rentals{% endblock head_title %}
{% load crispy_forms_tags %}
{% block head_extra %}{{ form.media }}{% endblock head_extra %}

{% block content %}
<div class="w3-row w3-padding w3-border">
	<div class="w3-col s12">
    <form method="POST" class="w3-container" action="" enctype="multipart/form-data">{% csrf_token %}
      <div>
        <div class="w3-col l4 w3-padding">
          {{ form.title|as_crispy_field }}
        </div>
        <div class="w3-col l3 w3-padding">
          {{ form.image|as_crispy_field }}
        </div>
        <div class="w3-col l3 w3-padding">
          {{ form.draft|as_crispy_field }}
        </div>
        <div class="w3-col l2 w3-padding">
          <button type="submit" class='w3-button w3-blue'>Submit</button>
        </div>
      </div>
      <div class="w3-col sm12 w3-padding">
        {{ form.content|as_crispy_field }}
      </div>
		</form>
	</div>
</div>

{% endblock content %}
{% block javascript %}
{{ block.super }}
<script src="https://cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
  <script>
    $(document).ready(function () {
      const editor = document.getElementById("id_content");
      CKEDITOR.replace(editor.name, {
        allowedContent: true,
        startupShowBorders: false,
        // width: 400,
        removePlugins: 'elementspath,magicline',
        removeButtons: 'Strike,Subscript,Superscript,Anchor,Styles,Specialchar,MediaEmbed,oembed,ShowBlocks,PageBreak,Cut,PasteText,PasteFromWord,Undo,Redo,Copy,Find,Replace,SelectAll,Scayt,Source,Save,NewPage,DocProps,Print,Image,Table,About'
      });
    });
</script>
{% endblock %}

construction/project-master/posts/templates/post_form1.html
{% extends "base1.html" %}
{% load crispy_forms_tags %}

{% block head_extra %} 
{{ form.media }}

{% endblock head_extra %}



{% block content %}
<div class='col-sm-6'>
<h1>Preview</h1>
<hr/>
<div class='content-preview'>
    <h3 id='preview-title'></h3>
    <p id='preview-content'></p>
</div>
</div>
<div class='col-sm-6'>
<h1>Form</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Create Post' />
</form>
</div>
{% endblock content %}