construction/project-master/posts/urls.py
from django.urls import path
from posts import views

app_name = "posts"

urlpatterns = [
	path('list', views.PostListView.as_view(), name="list"),
 	path('create/', views.PostCreateUpdateView.as_view(), name='create'),
 	path('<str:slug>/', views.PostDetailView.as_view(), name='detail'),
 	path('<str:slug>/edit/', views.PostCreateUpdateView.as_view(), name='update'),
 	# path('<slug>/delete/', views.post_delete),
]

construction/project-master/project/urls.py
from django.urls import include, path
from django.contrib import admin
from mains.views import HomeView, about_view, privacy_policy_view, ContactView, PurchaseHistoryView

from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "FOUR SQUARE RENTAL"
admin.site.site_title = "FOUR SQUARE RENTAL Admin Portal"
admin.site.index_title = "Welcome to FOUR SQUARE RENTAL Portal"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("contact/", ContactView.as_view(), name="contact"),
    path("agents/", include("agents.urls", namespace="agents")),
    path("", HomeView.as_view(), name="home"),
    path("property/",include('properties.urls',namespace='properties')),
    path("purchase-history/", PurchaseHistoryView.as_view(), name="purchase_history"),
    path("accounts/", include('allauth.urls')),
    path("about/", about_view,name="about"),
    path("privacy_policy/", privacy_policy_view,name="privacy_policy"),
    path("blog/", include('posts.urls', namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

construction/project-master/properties/urls.py
from django.urls import path
from properties.views import RemoveFromPurchaseList, CheckoutPurchaseView, RentPropertyView, BuyPropertyListView, RentPropertyListView, PostInspectionView, PropertyView, BuyPropertyView


app_name = "properties"


urlpatterns=[
  path("remove/<int:pk>/<str:type>/", RemoveFromPurchaseList.as_view(), name='remove_property'),
  path("detail/<str:slug>/", PropertyView.as_view(), name='individual_property'),
  path("buy-list/", BuyPropertyListView.as_view(), name='buy_property_list'),
  path("rent-list/", RentPropertyListView.as_view(), name='rent_property_list'),
  path("inspection/<int:pk>/", PostInspectionView.as_view(), name='property_inspection'),
  path("buy/<int:pk>/", BuyPropertyView.as_view(), name='property_buy'),
  path("rent/<int:pk>/", RentPropertyView.as_view(), name='property_rent'),
  path("checkout/", CheckoutPurchaseView.as_view(), name='checkout_purchase'),
]

construction/project-master/mains/models.py
from django.db import models

# Create your models here.

def upload_location(instance, filename):
	return "%s" %(filename)

class SlideImage(models.Model):

	description = models.CharField(max_length=100)
	image = models.ImageField(upload_to=upload_location)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __str__(self):
		  return "%s Posted on: %s" % (self.description,self.timestamp)


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=225)
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return self.name

construction/project-master/mains/forms.py
from django import forms
from allauth.account.forms import SignupForm


class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=225)
    last_name = forms.CharField(max_length=225)

    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        return user

construction/project-master/mains/views.py
from django.shortcuts import render, redirect
from itertools import chain
from django.urls import reverse
from properties.models import Property, OrderProperty, RentProperty
from django.contrib import messages

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q, Sum
from django.views.generic import View, ListView

from django.core.mail import send_mail
from django.conf import settings 
from properties.utils import handle_discounts
from django.http import JsonResponse
from django.core.mail import send_mail
from project.settings import EMAIL_HOST_USER
from mains.models import Contact, SlideImage
from properties.models import OrderProperty, RentProperty

# Create your views here.

class HomeView(ListView):
    model = Property
    template_name = 'index.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        qs = self.get_queryset()
        query=request.GET.get("q")
        if query:
            qs = qs.filter(
              Q(name__icontains=query) |
              Q(description__icontains=query) |
              Q(price__icontains=query)
            ).distinct()
        self.object_list = qs
        context = self.get_context_data(object_list=self.object_list)
        return render(request, self.template_name, context=context)
    
    def get_queryset(self):
        qs = Property.objects.filter(sold=False)
        return qs

    def get_context_data(self, **kwargs):
        ctx = super(HomeView, self).get_context_data(**kwargs)
        ctx['photos'] = SlideImage.objects.all()
        if self.request.user.is_authenticated:
            orders = OrderProperty.objects.filter(user=self.request.user, paid=False).select_related('property', 'user')
            rents = RentProperty.objects.filter(user=self.request.user, paid=False).select_related('property', 'user')
            result_list = list(chain(orders, rents))
            total_price = 0
            for i in result_list:
              total_price += i.property.price
            ctx['orders'] = result_list
            ctx['total_price'] = total_price
        return ctx


def about_view(request):
	template = "about.html"
	context = {}
	return render(request,template,context)


def privacy_policy_view(request):
	template = "privacy_policy.html"
	context = {}
	return render(request,template,context)


class ContactView(View):

    def send_email(self, data, *args):
        send_mail(
            subject = data.get('subject'),
            message = data.get('message'),
            from_email = EMAIL_HOST_USER,
            recipient_list = [data.get('email')],
            fail_silently=False
        )

    def post(self, request, *args, **kwargs):
        data = request.POST
        c_obj = Contact(
          name=data['name'],
          email=data['email'],
          subject=data['subject'],
          message=data['message']
        )
        c_obj.save()
        self.send_email(data)
        messages.success(request, "Thank you for reaching out. We will get back to you soon.")
        return redirect(reverse('home'))


class PurchaseHistoryView(ListView):
    model = OrderProperty
    template_name = 'history.html'

    def get_queryset(self):
        qs = OrderProperty.objects.filter(paid=True).select_related('property')
        result_list = list(chain(qs, RentProperty.objects.filter(paid=True).select_related('property')))
        return result_list

    def get_context_data(self, **kwargs):
        ctx = super(PurchaseHistoryView, self).get_context_data(**kwargs)
        # ctx['rent_list'] = RentProperty.objects.filter(paid=True)
        return ctx

construction/project-master/mains/templates/about.html
{% extends "base.html" %}

{% block title %}Mellif | About Team Mellif. {% endblock title %}

{% block page_title %} About Us {% endblock page_title %}


{% block meta_head %}

The best cakes in your hometown, Kathmandu, Nepal delivered at your doorstep. Urgent cakes available in less than 1 hour. Cash On Delivery. Birthday Cake, Anniversary Cake, Wedding Cakes. Custom Cakes. Your own designs. Party cakes. Cake related with sports like Football and many other surprise cakes. Gifts and Pillows.

{% endblock meta_head %}

{% block content %}
	
<div class="w3-container w3-margin-bottom w3-margin-top">
	<p>Mellif  is currently Kathmandu based dedicated seller of quality cakes. We are Nepali owned and managed, established in 2017. Our goal is to make your occasions beautiful with surprises and always maintaining the quality of our product.
	<p>
	<p>
	Our cakes are made with only the finest, freshest ingredients by our experienced chef. We've grown to offer more and more of the finest cakes with lots of gift hampers. There is no better way to celebrate a special occasion than to send a little indulgence from someone who cares. We fully believe on quality and customer satisfaction.
	</p><br> 

	<h3>Vision</h3>
	<p>
	MelliF’s  vision is to achieve a remarkable market in Nepal E-Commerce sector in bakery area.
	</p><br>

	<h3>Mission</h3>
	<p>
	Our Mission  is to proactively provide satisfaction with timely delivery, real time order via website and full customer satisfaction.
	</p>

	<h3>Our team </h3>
	<p>
	We were formed with different sector but our aim to make a successive place of bakery in Nepal’s E-Commerce. 
	<h3>
	<i>“Quality product with customer satisfaction is our main aim”</i>

	</h3>

</div>


{% endblock content %}



{% block script %}

$(document).ready(function(){
    $( ".about" ).addClass( "w3-dark-grey" );
    var elmnt = document.getElementById("mySidebar");
    elmnt.scrollLeft = 0;
    elmnt.scrollTop = 1000;
});

{% endblock script %}

construction/project-master/mains/templates/anniversary.html
{% extends "base.html" %}
{% block title %} Mellif | Cake for Anniversary {% endblock title %}

{% block page_title %} Anniversary Cakes {% endblock page_title %}

{% block meta_head %}

The best cakes in your hometown, Kathmandu, Nepal delivered at your doorstep. Urgent cakes available in less than 1 hour. Cash On Delivery. Anniversary Cake, Wedding Cakes. Custom Cakes. Your own designs. Party cakes. Gifts and Pillows.

{% endblock meta_head %}

{% block content %}
<div class="w3-row">

        {% for each in cakes %}
        <div class="w3-col l3 s6">
          <div class="w3-container">
            <div class="w3-display-container">
              <img alt="{{ each.name }}" src="{{ each.image.url }}" style="width:100%">
              <!-- <span class="w3-tag w3-display-topleft">New</span> -->
              <div class="w3-display-middle w3-display-hover">
                <a href="{{ each.get_absolute_url }}">
                <button class="w3-button w3-red">Buy now <i class="fa fa-shopping-cart"></i></button>
                </a>
              </div>
            </div>
            <div style="padding-top: 10px;">
            <h3><small>{{ each.name|truncatechars_html:15 }}<br><b>Rs: {{ each.price }}/-</b></small></h3>
            </div>
          </div>
        </div>
        {% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if cakes.has_previous %}
            <a href="?{{ page_request_var }}={{ cakes.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" style="color: blue;">previous</a>
        {% endif %}

        <span class="current">
            Page {{ cakes.number }} of {{ cakes.paginator.num_pages }}.
        </span>

        {% if cakes.has_next %}
            <a href="?{{ page_request_var }}={{ cakes.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" style="color: blue;">next</a>
        {% endif %}
    </span>
</div>

{% endblock content %}


{% block script %}

$(document).ready(function(){
    $( "#anniversary" ).addClass( "w3-dark-grey" );
});

{% endblock script %}

construction/project-master/mains/templates/congratulate.html
{% extends "base.html" %}
{% block title %} Mellif | Cakes for congratulating  {% endblock title %}

{% block page_title %} Congratulation {% endblock page_title %}

{% block meta_head %}

The best cakes in your hometown, Kathmandu, Nepal delivered at your doorstep. Urgent cakes available in less than 1 hour. Cash On Delivery. cakes Congratulation. Custom Cakes. Your own designs. Cake related with sports like Football and many other surprise cakes. Gifts and Pillows.

{% endblock meta_head %}

{% block content %}
<div class="w3-row">

        {% for each in cakes %}
        <div class="w3-col l3 s6">
          <div class="w3-container">
            <div class="w3-display-container">
              <img alt="{{ each.name }}" src="{{ each.image.url }}" style="width:100%">
              <!-- <span class="w3-tag w3-display-topleft">New</span> -->
              <div class="w3-display-middle w3-display-hover">
                <a href="{{ each.get_absolute_url }}">
                <button class="w3-button w3-red">Buy now <i class="fa fa-shopping-cart"></i></button>
                </a>
              </div>
            </div>
            <div style="padding-top: 10px;">
            <h3><small>{{ each.name|truncatechars_html:15 }}<br><b>Rs: {{ each.price }}/-</b></small></h3>
            </div>
          </div>
        </div>
        {% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if cakes.has_previous %}
            <a href="?{{ page_request_var }}={{ cakes.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" style="color: blue;">previous</a>
        {% endif %}

        <span class="current">
            Page {{ cakes.number }} of {{ cakes.paginator.num_pages }}.
        </span>

        {% if cakes.has_next %}
            <a href="?{{ page_request_var }}={{ cakes.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" style="color: blue;">next</a>
        {% endif %}
    </span>
</div>

{% endblock content %}


{% block script %}

$(document).ready(function(){
    $( "#congratulate" ).addClass( "w3-dark-grey" );
});

{% endblock script %}

construction/project-master/mains/templates/festivals.html
{% extends "base.html" %}
{% block title %} Mellif | Cakes for Festivals {% endblock title %}

{% block page_title %} Festivals {% endblock page_title %}

{% block meta_head %}

The best cakes in your hometown, Kathmandu, Nepal delivered at your doorstep. Urgent cakes available in less than 1 hour. Cash On Delivery. Cakes for Festivals. Gifts and Pillows.

{% endblock meta_head %}

{% block content %}
<div class="w3-row">

        {% for each in cakes %}
        <div class="w3-col l3 s6">
          <div class="w3-container">
            <div class="w3-display-container">
              <img alt="{{ each.name }}" src="{{ each.image.url }}" style="width:100%">
              <!-- <span class="w3-tag w3-display-topleft">New</span> -->
              <div class="w3-display-middle w3-display-hover">
                <a href="{{ each.get_absolute_url }}">
                <button class="w3-button w3-red">Buy now <i class="fa fa-shopping-cart"></i></button>
                </a>
              </div>
            </div>
            <div style="padding-top: 10px;">
            <h3><small>{{ each.name|truncatechars_html:15 }}<br><b>Rs: {{ each.price }}/-</b></small></h3>
            </div>
          </div>
        </div>
        {% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if cakes.has_previous %}
            <a href="?{{ page_request_var }}={{ cakes.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" style="color: blue;">previous</a>
        {% endif %}

        <span class="current">
            Page {{ cakes.number }} of {{ cakes.paginator.num_pages }}.
        </span>

        {% if cakes.has_next %}
            <a href="?{{ page_request_var }}={{ cakes.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" style="color: blue;">next</a>
        {% endif %}
    </span>
</div>

{% endblock content %}


{% block script %}

$(document).ready(function(){
    $( "#festivals" ).addClass( "w3-dark-grey" );
});

{% endblock script %}

construction/project-master/mains/templates/history.html
{% extends "base.html" %}
{% block title %}Four Square Rental | Best in Business{% endblock title %}
{% block page_title %} Purchase History {% endblock page_title %}


{% block history %}w3-dark-grey{% endblock %}
{% block meta_head %}
The best properties in Australia with reasonable deals.
{% endblock %}{% block content %}
  <div class="w3-row w3-container w3-margin-top">
    <table class="w3-table w3-striped w3-bordered w3-border w3-hoverable w3-white">
      <tr>
        <th>S.N</th>
        <th>Product</th>
        <th>Type</th>
        <th>Price</th>
      </tr>
      {% for obj in object_list %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ obj.property }}</td>
        <td>{{ obj.property.type }}</td>
        <td>${{ obj.property.price }}</td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="4" style="text-align: center;">You don't have a Purchase History</td>
      </tr>
      {% endfor %}
    </table><br>
  </div>
{% endblock %}

construction/project-master/mains/templates/index.html
{% extends "base.html" %}

{% block title %}Four Square Rental | Best in Business{% endblock title %}

{% block page_title %} Home {% endblock page_title %}

<!-- for navigation  -->
{% block home %}w3-dark-grey{% endblock %}
<!-- for the meta data to base file  -->
{% block meta_head %}
The best properties in Australia with reasonable deals.
{% endblock %}

{% block cart %}
  <a href="javascript:void(0)" onclick="document.getElementById('addtocart').style.display='block'">
  <span class="badge" style="background-color: darkred;">{{ orders|length }}</span><i class="fa fa-shopping-cart w3-margin-right"></i></a>
{% endblock %}

{% block search %}
  <form method="GET" action=''>{% csrf_token %}
      <div class="input-group">
        <input type="text" class="form-control" name="q" placeholder="Search properties..." value={{ request.GET.q }}>
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
        </div>
      </div>
  </form>
{% endblock %}

{% block content %}

      <!-- Image header -->
      <div class="w3-display-container w3-container">
      {% for single in photos %}
        <img alt="Cakes and gifts" src="{{ single.image.url }}" class="mySlides w3-animate-opacity" style="width:100%">
       {% endfor %}
        <div class="w3-display-topleft w3-text-white" style="padding:24px 48px">
          <h1 class="w3-hide-small">Featured on Four Square Rental</h1>
          <h3 class="w3-hide-small">Properties 2020</h3>
          <p><a href="{% url 'posts:list' %}" class="w3-button w3-black w3-large shop">View More</a></p>
        </div>
      </div>

      <!-- Product grid -->
      <hr>
      <div class="w3-row">
        <p style="color: #4f0019;">&nbsp; &nbsp; You are viewing top properties</p>
        {% for each in object_list %}
        <div class="w3-col l3 m6 w3-mobile w3-margin-bottom">
          <div class="w3-container">
            <div class="w3-display-container">
              <img alt="{{ each.name }}" src="{{ each.image.url }}" style="height: 260px;width:100%;object-fit:cover;">
              <!-- <span class="w3-tag w3-display-topleft">New</span> -->
              <div class="w3-display-middle w3-display-hover">
                <a href="{{ each.get_absolute_url }}">
                <button class="w3-button w3-red">View&nbsp;<i class="fa fa-arrows"></i></button>
                </a>
              </div>
            </div>
            <div style="padding-top: 10px;">
              <h3><small>{{ each.name|truncatechars_html:15 }}</small></h3> <p><small>Rs: {{ each.price }}/-</small></p>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>

      <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
      
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
      
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
      </div>
{% endblock content %}

{% block modal %}
  {% if request.user.is_authenticated %}
    <div id="addtocart" class="w3-modal" style="z-index:5;">
      <div class="w3-modal-content w3-animate-zoom">
        <div class="w3-container w3-padding w3-red">
          <span onclick="document.getElementById('addtocart').style.display='none'"
          class="w3-button w3-red w3-right w3-xxlarge"><i class="fa fa-remove"></i></span>
          <h2>Your Bookings</h2>
        </div>
        <div class="w3-panel">
          <div class="row container-fluid">
            <div class="col-sm-12">
              <div class="table-responsive">          
                  <table class="table">
                    <thead>
                      <tr>
                        <th>S.N</th>
                        <th>Product Name</th>
                        <th>Price</th>
                        <th>Type</th>
                        <th></th>
                      </tr>
                    </thead>
                      <tbody>
                      {% if orders %}
                      {% for item in orders %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                          <a href="{{ item.property.get_absolute_url }}" style="color: rgba(27, 43, 135, 0.92);">
                            {{ item.property.name }}
                          </a>
                        </td>
                        <td>${{ item.property.price }}/-</td>
                        <td>
                          {% if item.property.type == 'rent' %}
                            Rented
                          {% else %}
                            Bought
                          {% endif %}
                        </td>
                        <td><a href="{% url 'properties:remove_property' item.pk item.property.type %}" class="w3-button w3-red w3-card-4 w3-tiny">X</a></td>
                      </tr>
                      {% endfor %}
                      <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><b>Total: </b> $<span style="color: red;">{{ total_price }}/-</span></td>
                        <td></td>
                      </tr>
                      {% else %}
                      <tr>
                        <td colspan="5" style="text-align: center;">Booking list is empty</td>
                      </tr>
                      {% endif %}
                      </tbody>
                  </table>
                  </div>
            </div>
            {% if orders %}
            <div class="w3-container w3-padding">
              <button id="idCheckout" style="float: right;" class="w3-button w3-black">Checkout</button>
            </div>
            <form id="payment-form" class="w3-container w3-padding" style="display: none;">
              <label for="card-element" class="w3-margin-bottom" id="cardLabel">Card Details</label>
              <div id="card-element"></div>
              <div id="card-errors" class="w3-red" role="alert"></div>
              <button id="submit" style="width: 100%;" class="w3-button w3-blue w3-margin-top">Pay</button>
            </form>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

{% block javascript %}
  {{ block.super }}
  <script src="https://js.stripe.com/v3/"></script>
  <script>
    var stripe = Stripe('pk_test_51HSIKdHCepC6wmdulBH3JxH8Ydb2jGYkD5GHqt4fs3Dx5CX9QIzzeUuAJ8On1SUu2kyWiI6xLZqgyMWVHoK110PS00MOv5rqvQ');
    var elements = stripe.elements();
    var style = {
      base: { color: "#32325d" }
    };
    var currentError = null;
    var cardElement = elements.create('card', { style: style });
    document.getElementById('idCheckout').onclick = function() {
      document.getElementById('payment-form').style.display = 'block';
      cardElement.mount('#card-element');
    }
    cardElement.on('change', ({error}) => {
      const displayError = document.getElementById('card-errors');
      if (error) {
        displayError.style.marginTop = '16px';
        displayError.textContent = error.message;
        currentError = error.message;
      } else {
        displayError.style.marginTop = '0px';
        displayError.textContent = '';
        currentError = null;
      }
    });

    var form = document.getElementById('payment-form');
    var clientSecret = '123_secret_sk_test_51HSIKdHCepC6wmduzgaHiM4hKBnPw0HTdwif6OAQVXt3F4YogSuukPuNAduEIUn6NT7wyESK3wBmpefPFYIAyREq00LahrYCwh';
    form.addEventListener('submit', function(ev) {
      ev.preventDefault();
      if (!currentError) {
        window.location = "{% url 'properties:checkout_purchase' %}";
      }
      // stripe.confirmCardPayment(clientSecret, {
      //   payment_method: {
      //     card: cardElement,
      //     billing_details: {
      //       name: '{{ request.user.username }}'
      //     }
      //   }
      // }).then(function(result) {
      //   if (result.error) {
      //     alert('Error in stripe')
      //   } else {
      //     if (result.paymentIntent.status === 'succeeded') {
      //       alert('successful');
      //     }
      //   }
      // });
    });
  </script>
  <script>
    var myIndex = 0;
    carousel();

    function carousel() {
        var i;
        var x = document.getElementsByClassName("mySlides");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";  
        }
        myIndex++;
        if (myIndex > x.length) {myIndex = 1}    
        x[myIndex-1].style.display = "block";  
        setTimeout(carousel, 5000); // Change image every 2 seconds
    }
  </script>
{% endblock %}

construction/project-master/mains/templates/marriage.html
{% extends "base.html" %}
{% block title %} Mellif | Cakes for Marriage {% endblock title %}

{% block page_title %} Marriage  {% endblock page_title %}

{% block meta_head %}

Wedding Cakes. The best cakes in your hometown, Kathmandu, Nepal delivered at your doorstep. Urgent cakes available in less than 1 hour. Cash On Delivery.  Anniversary Cake. Custom Cakes. Your own designs. Gifts and Pillows.

{% endblock meta_head %}

{% block content %}
<div class="w3-row">

        {% for each in cakes %}
        <div class="w3-col l3 s6">
          <div class="w3-container">
            <div class="w3-display-container">
              <img alt="{{ each.name }}" src="{{ each.image.url }}" style="width:100%">
              <!-- <span class="w3-tag w3-display-topleft">New</span> -->
              <div class="w3-display-middle w3-display-hover">
                <a href="{{ each.get_absolute_url }}">
                <button class="w3-button w3-red">Buy now <i class="fa fa-shopping-cart"></i></button>
                </a>
              </div>
            </div>
            <div style="padding-top: 10px;">
            <h3><small>{{ each.name|truncatechars_html:15 }}<br><b>Rs: {{ each.price }}/-</b></small></h3>
            </div>
          </div>
        </div>
        {% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if cakes.has_previous %}
            <a href="?{{ page_request_var }}={{ cakes.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" style="color: blue;">previous</a>
        {% endif %}

        <span class="current">
            Page {{ cakes.number }} of {{ cakes.paginator.num_pages }}.
        </span>

        {% if cakes.has_next %}
            <a href="?{{ page_request_var }}={{ cakes.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" style="color: blue;">next</a>
        {% endif %}
    </span>
</div>

{% endblock content %}


{% block script %}

$(document).ready(function(){
    $( "#marriage" ).addClass( "w3-dark-grey" );
});

{% endblock script %}

construction/project-master/mains/templates/new_year.html
{% extends "base.html" %}
{% block title %} Mellif | Cakes on New Year Special {% endblock title %}

{% block page_title %} New year  {% endblock page_title %}

{% block meta_head %}

Wedding Cakes. The best cakes in your hometown, Kathmandu, Nepal delivered at your doorstep. Urgent cakes available in less than 1 hour. Cash On Delivery. New Year Cake. Custom Cakes. Celebrate New Year. Your own designs. Gifts and Pillows.

{% endblock meta_head %}

{% block content %}
<div class="w3-row">

        {% for each in cakes %}
        <div class="w3-col l3 s6">
          <div class="w3-container">
            <div class="w3-display-container">
              <img alt="{{ each.name }}" src="{{ each.image.url }}" style="width:100%">
              <!-- <span class="w3-tag w3-display-topleft">New</span> -->
              <div class="w3-display-middle w3-display-hover">
                <a href="{{ each.get_absolute_url }}">
                <button class="w3-button w3-red">Buy now <i class="fa fa-shopping-cart"></i></button>
                </a>
              </div>
            </div>
            <div style="padding-top: 10px;">
            <h3><small>{{ each.name|truncatechars_html:15 }}<br><b>Rs: {{ each.price }}/-</b></small></h3>
            </div>
          </div>
        </div>
        {% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if cakes.has_previous %}
            <a href="?{{ page_request_var }}={{ cakes.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" style="color: blue;">previous</a>
        {% endif %}

        <span class="current">
            Page {{ cakes.number }} of {{ cakes.paginator.num_pages }}.
        </span>

        {% if cakes.has_next %}
            <a href="?{{ page_request_var }}={{ cakes.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" style="color: blue;">next</a>
        {% endif %}
    </span>
</div>

{% endblock content %}


{% block script %}

$(document).ready(function(){
    $( "#new_year" ).addClass( "w3-dark-grey" );
});

{% endblock script %}

construction/project-master/mains/templates/privacy_policy.html
{% extends "base.html" %}

{% block title %}Privacy Policy{% endblock title %}
{% block content %}
	
<div class="w3-container w3-margin-bottom w3-margin-top">
	<h3>Privacy Policy</h3>
	<p><a href="{% url 'home' %}">We</a> do not collect or publish any personal information.
		<br>
	If you would like to report any violations of this policy, please contact us.</p>	
</div>


{% endblock content %}