construction/project-master/posts/urls.py
from django.urls import path
from posts import views

app_name = "posts"

urlpatterns = [
	path('list', views.PostListView.as_view(), name="list"),
 	path('create/', views.PostCreateUpdateView.as_view(), name='create'),
 	path('<str:slug>/', views.PostDetailView.as_view(), name='detail'),
 	path('<str:slug>/edit/', views.PostCreateUpdateView.as_view(), name='update'),
 	# path('<slug>/delete/', views.post_delete),
]

construction/project-master/project/urls.py
from django.urls import include, path
from django.contrib import admin
from mains.views import HomeView, about_view, privacy_policy_view, ContactView, PurchaseHistoryView

from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "FOUR SQUARE RENTAL"
admin.site.site_title = "FOUR SQUARE RENTAL Admin Portal"
admin.site.index_title = "Welcome to FOUR SQUARE RENTAL Portal"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("contact/", ContactView.as_view(), name="contact"),
    path("agents/", include("agents.urls", namespace="agents")),
    path("", HomeView.as_view(), name="home"),
    path("property/",include('properties.urls',namespace='properties')),
    path("purchase-history/", PurchaseHistoryView.as_view(), name="purchase_history"),
    path("accounts/", include('allauth.urls')),
    path("about/", about_view,name="about"),
    path("privacy_policy/", privacy_policy_view,name="privacy_policy"),
    path("blog/", include('posts.urls', namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

construction/project-master/properties/urls.py
from django.urls import path
from properties.views import RemoveFromPurchaseList, CheckoutPurchaseView, RentPropertyView, BuyPropertyListView, RentPropertyListView, PostInspectionView, PropertyView, BuyPropertyView


app_name = "properties"


urlpatterns=[
  path("remove/<int:pk>/<str:type>/", RemoveFromPurchaseList.as_view(), name='remove_property'),
  path("detail/<str:slug>/", PropertyView.as_view(), name='individual_property'),
  path("buy-list/", BuyPropertyListView.as_view(), name='buy_property_list'),
  path("rent-list/", RentPropertyListView.as_view(), name='rent_property_list'),
  path("inspection/<int:pk>/", PostInspectionView.as_view(), name='property_inspection'),
  path("buy/<int:pk>/", BuyPropertyView.as_view(), name='property_buy'),
  path("rent/<int:pk>/", RentPropertyView.as_view(), name='property_rent'),
  path("checkout/", CheckoutPurchaseView.as_view(), name='checkout_purchase'),
]

construction/project-master/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}

<html>
<head>

<title>{% block title %}{% endblock title %}</title>
    
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="description" content="{% block meta_head %}{% endblock meta_head %}"/>

<meta name="keywords" content="Best Cakes In Kathmandu, Nepal. Birthday Cake, Anniversary Cake, Wedding Cakes, Send cakes to Nepal. Party Cakes, Sports cake, Football, lovely. Gifts. Pillows" />


<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
<!-- <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="shortcut icon" href="{% static 'logo.png' %}" type="image/png">
<link rel="stylesheet" href="{% static 'main.css' %}">
<link rel="stylesheet" href="{% static 'main2.css' %}">
<link rel="stylesheet" href="{% static 'owl.carousel.css' %}">

<style>
  .w3-sidebar a {font-family: "Roboto", sans-serif;}
  body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}
  .mySlides {display:none;}
  .cake-order .control-label{
    display: none;
  }
  .review {
      background-color: black;
      background-size: cover;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
  }

  .review h3 {
    font-family: "Roboto", sans-serif;
    color: coral;
    font-size: 2em;
    text-align: center;
    text-transform: uppercase;
  }
  .test-review p {
      font-size: 16px;
      font-weight: 400;
      line-height: 2.2em;
      margin: 1em 0;
      padding: 22px 25px;
      color: #eee;
    background: rgba(165, 163, 163, 0.32);
  }
</style>
</head>
<body class="w3-content" style="max-width:1200px">

    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-bar-block w3-white w3-collapse w3-top" style="z-index:5;width:220px" id="mySidebar">
      <div class="w3-container w3-display-container w3-padding-16">
        <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-display-topright">
          </i>
      <div class="w3-wide"><a href="{% url 'home' %}"><img alt="Company logo" src="{% static 'logo.png' %}" style="width:100%;"/></a></div>
      </div>

      <div class="w3-padding-64 w3-large w3-text-grey" style="font-weight:bold;">
          <a href="{% url 'home' %}" class="w3-bar-item w3-button {% block home %}{% endblock %}" id="birthday">Home</a>
          <a onclick="myAccFunc()" href="javascript:void(0)" class="w3-button w3-block w3-left-align" id="myBtn">
            Properties <i class="fa fa-caret-down"></i>
          </a>
          <div id="demoAcc" class="w3-bar-block w3-hide w3-padding-large w3-medium">
            <a href="{% url 'properties:buy_property_list' %}" class="w3-bar-item w3-button {% block buy_property %}{% endblock %}" id="surprise">Buy Properties</a>
            <a href="{% url 'properties:rent_property_list' %}" class="w3-bar-item w3-button {% block rent_property %}{% endblock %}" id="anniversary">Rent Properties</a>
            <a href="#" class="w3-bar-item w3-button" id="valentines_day">Invest on Us</a>
          </div>
          <a href="{% url 'agents:list' %}" class="w3-bar-item w3-button {% block agents %}{% endblock %}" id="festivals">Our Agents</a>
          {% if request.user.is_authenticated %}
          <a href="{% url 'purchase_history' %}" class="w3-bar-item w3-button {% block history %}{% endblock %}" id="history">Purchase History</a>
          {% endif %}
          <a href="{% url 'posts:list' %}" target="_blank" class="w3-bar-item w3-button" id="party">Blog</a>
      </div>

      <a href="#footer" class="w3-bar-item w3-button w3-padding">Contact</a> 
      <a href="{% url 'about' %}" class="w3-bar-item w3-button w3-padding about">About US</a>
    </nav>

    <!-- Top menu on small screens -->
    <header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge" style="z-index: 3;">

      <div class="col-xs-4 col-sm-2 col-md-2 w3-margin-top"><a href="{% url 'home' %}"><img alt="Company logo" src="{% static 'logo3.png' %}" style="max-height: 37px;"/></a></div>

      <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>

    </header>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

    <!-- page content -->
    <div class="w3-main" style="margin-left:250px">

      <!-- Push down content on small screens -->
      <div class="w3-hide-large" style="margin-top:83px"></div>
      {% include 'message.html' %}
        <!-- Top header -->
        <header class="w3-container w3-xlarge">
          <!-- For search -->
          <div class="w3-margin-top row">

            <div class="col-xs-3 col-sm-3">
              <p class="w3-left"><b>{% block page_title %}{% endblock page_title %}</b></p>
            </div>

            <div class="col-xs-offset-3 col-xs-6 col-sm-offset-5 col-sm-4">
              {% block search %}{% endblock %}
              <div class="w3-right">
              {% if request.user.is_authenticated %}
                {% block cart %}{% endblock %}
                <a href="{% url 'account_logout' %}"><button type="button" class="w3-button w3-red w3-small">Logout</button></a>
              {% else %}
                <a href="{% url 'account_login' %}"><button type="button" class="w3-button w3-red w3-small">Login</button></a>
              {% endif %}
            </div>
          </div>
        </div>
      </header>

      {% block content %}

      {% endblock content %}
      
      <!-- Crousal section -->
       <div class="w3-padding-16 w3-center">
          <div id="testimonials" class="review">
            <div>
              <h3><small style="color: coral;">Special Offers</small></h3>
                  <div>
                      <div class="sreen-gallery-cursual">
                        
                   <div id="owl-demo" class="owl-carousel">
                           <div class="item-owl">
                            <div class="test-review">
                              <p><img alt="left quote" src="{% static 'left-quote.png' %}" alt="">5% discount on your first order<img alt="right quote" src="{% static 'right-quote.png' %}" alt=""></p>
                            </div>
                          </div>
                           <div class="item-owl">
                              <div class="test-review">
                                  <p><img alt="left quote" src="{% static 'left-quote.png' %}" alt="">Free Inspection<img alt="right quote" src="{% static 'right-quote.png' %}" alt=""></p>
                              </div>
                          </div>
                           <div class="item-owl">
                            <div class="test-review">
                                <p><img alt="left quote" src="{% static 'left-quote.png' %}" alt="">Pay in installments.<img alt="right quote" src="{% static 'right-quote.png' %}" alt=""></p>
                            </div>
                          </div>
                          </div>
                      </div>
          </div>
        </div>
      </div>  
        
      </div>

      <!-- Footer -->
      <footer class="w3-padding-64 w3-light-grey w3-small w3-center" id="footer">
        <div class="w3-row-padding">
          <div class="w3-col s4" id="custom-cake">
            <h4>Contact</h4>
            <p>Questions? Go ahead</p>
            <form action="{% url 'contact' %}" method="POST" class="cake-order" enctype="multipart/form-data">{% csrf_token %}
              <p><input class="w3-input w3-border" type="text" placeholder="Name" name="name" required></p>
              <p><input class="w3-input w3-border" type="email" placeholder="Email" name="email" required></p>
              <p><input class="w3-input w3-border" type="text" placeholder="Subject" name="subject" required></p>
              <p><textarea class="w3-input w3-border" placeholder="Message" name="message" required></textarea></p>
              <button type="submit" class="w3-button w3-block w3-black">Submit</button>
            </form>
          </div>

          <div class="w3-col s4">
            <h4>Links</h4>
            <p><a href="{% url 'posts:list' %}">Blog</a></p>
            <p><a href="{% url 'about' %}">About us</a></p>
            <p><a href="{% url 'privacy_policy' %}">Privacy Policy</a></p>
            <p><a href="#">Help</a></p>
          </div>

          <div class="w3-col s4">
            <h4>Office</h4>
            <p><a href="#" target="_blank"><i class="fa fa-fw fa-map-marker"></i> Four Square Rental
            </a></p>
            <p><i class="fa fa-fw fa-phone"></i> 2367676891</p>
            <br>
            <h5>We accept</h5>
            <p><i class="fa fa-fw fa-credit-card"></i> Credit Card</p>
            <br>
            <h5>Follow Us:</h5>
            <a href="#" target="_blank"><i class="fa fa-facebook-official w3-hover-opacity w3-large"></i></a>
            <a href="#" target="_blank"><i class="fa fa-instagram w3-hover-opacity w3-large"></i></a>
            <a href="#" target="_blank"><i class="fa fa-pinterest-p w3-hover-opacity w3-large"></i></a>
          </div>
        </div>
      </footer>

      <div class="w3-black w3-center w3-padding-24">copyright ©2020</div>

      <!-- End page content -->
    </div>
    {% block modal %}{% endblock %}
  {% block javascript %}
  <script src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>
  <script async src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'owl.carousel.js' %}"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      $("#owl-demo").owlCarousel({
        items : 1,
        lazyLoad : true,
        autoPlay : true,
        navigation : false,
        navigationText :  false,
        pagination : true,
      });
    });
      // Accordion 
    function myAccFunc() {
        var x = document.getElementById("demoAcc");
        if (x.className.indexOf("w3-show") == -1) {
            x.className += " w3-show";
        } else {
            x.className = x.className.replace("w3-show", "");
        }
    }
    // Click on the "Jeans" link on page load to open the accordion for demo purposes
    document.getElementById("myBtn").click();
    function w3_open() {
        document.getElementById("mySidebar").style.display = "block";
        document.getElementById("myOverlay").style.display = "block";
    }

    function w3_close() {
        document.getElementById("mySidebar").style.display = "none";
        document.getElementById("myOverlay").style.display = "none";
    }
  </script>
  {% endblock %}
</body>
</html>

construction/project-master/templates/message.html
{% if messages %}
{% for message in messages %}
<div class="w3-panel {% if message.tags == 'success' %}w3-green{% endif %}{% if message.tags == 'warning' %}w3-yellow{% endif %}{% if message.tags == 'error' %}w3-red{% endif %}{% if message.tags == 'info' %}w3-blue{% endif %} w3-display-container">
  <span onclick="this.parentElement.style.display='none'"
  class="w3-button w3-large w3-display-topright">&times;</span>
  <h3 style="text-transform: capitalize;">{{ message.tags }}!</h3>
  <p>
    {% if "html_safe" in message.tags %} {{ message|safe }} {% else %} {{ message }} {% endif %}
  </p>
</div>
{% endfor %}
{% endif %}